<?php
namespace AppBundle\Repository;

/**
 * BreaksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreaksRepository extends \Doctrine\ORM\EntityRepository
{
    
}
